name: Deploy

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configurar .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Instalar .NET Wasm Tools
        run: dotnet workload install wasm-tools

      - name: Restaurar Dependências
        run: dotnet restore

      - name: Compilar
        run: dotnet build -c Release --no-restore

      - name: Publicar Blazor em docs
        run: dotnet publish blazor-chart-webassembly/blazor-chart-webassembly.csproj -c Release -o docs --nologo


      - name: Recriar .nojekyll
        run: touch docs/.nojekyll

      - name: Configurar GitHub Pages
        uses: actions/configure-pages@v4

      - name: Enviar artefato para Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs

      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
